name: conda

on:
  push:
    branches:
      - main

env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  recipe_path: deploy/conda/recipe
  env_yaml_path: deploy/conda/env/yaml
  VERSION: '0.0.2' # versioned by bump2version

jobs:
  condarise:
    # When merging to main and the commit message starts with 'Bump version:'
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Condarise
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Micromamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.4.9-0'
          environment-file: ${{ env.env_yaml_path }}/condabuild.yaml
      - name: 🐍 Conda pkg build and upload
        run: |
          conda mambabuild --R 4.1 ${recipe_path} --token ${atoken}
      - name: 🔖 Create tag
        uses: actions/github-script@v6
        env:
          LATEST_COMMIT_HASH: ${{ github.sha }}
        with:
          script: |
            const the_tag_name = 'refs/tags/v' + process.env.VERSION
            const the_sha = process.env.LATEST_COMMIT_HASH
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: the_tag_name,
              sha: the_sha
            })
